mutation Login($LoginInput: LoginInput!) {
    login(LoginInput: $LoginInput) {
        success
        OTP
        message
        data {
            access_token
            refresh_token
            about_me
            address
            area
            birth_date
            birth_place
            birth_time
            blood_group
            business_address
            business_category
            business_category_id
            business_logo
            business_sub_category
            business_sub_category_id
            city
            city_id
            committee
            committee_id
            company_name
            created_dt
            current_activity
            current_activity_id
            designation
            designation_id
            distance
            distinct_id
            education
            education_id
            email_address
            expectation
            expire_date
            facebook_profile
            father_name
            first_name
            gender
            gotra
            gotra_id
            head_id
            head_name
            head_sub_cast_id
            height
            hobby
            home_lat
            home_lng
            is_donor
            is_expired
            isImportant
            is_location_enable
            is_mangal
            is_rented
            is_shani
            is_spect
            last_login
            last_name
            local_address
            local_community
            local_community_id
            login_status
            marital_status
            marriage_date
            matched
            matrimony
            member_code
            member_count
            mosaad_id
            mossad
            mother_name
            native
            native_place_id
            nearBy
            occupation
            occupation_id
            office_lat
            office_lng
            online_status
            phone
            pincode
            profile_completed
            profile_percentage
            profile_pic
            region
            relation
            relation_id
            sharing_id
            state
            state_id
            status
            sub_cast_id
            sub_community
            sub_community_id
            updated_dt
            user_lat
            user_lng
            website
            weight
            work_details
            reminder_birth_date
            reminder_marriage_date
            reminder_expire_date
            matches
        }
    }
}
