buildscript {
    ext.kotlin_version = '2.0.0'
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
//        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath 'com.android.tools.build:gradle:8.1.4'
        classpath 'com.google.gms:google-services:4.3.13'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.github.ben-manes:gradle-versions-plugin:0.27.0'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.1'
    }
}

allprojects {

    repositories {
        google()
        mavenCentral()
        maven {url "https://maven.google.com"}
        maven { url 'https://jitpack.io' }
        maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    minSdkVersion = 21
    compileSdkVersion = 35
    // https://developer.android.com/studio/releases/build-tools
    buildToolsVersion = '28.0.3'
    FRESCO_VERSION = '2.0.0'
    // https://developer.android.com/topic/libraries/support-library/revisions
    SUPPORT_LIBRARY_VERSION = '27.1.1'
    RXJAVA2_VERSION = '2.2.3'
    RXANDROID2_VERSION = '2.1.0'
}