#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Wed Oct 03 00:28:14 IST 2018
apiSecret=fe485610cca4d1b2ff6b349949f30c59681636cd6aa5083dd6ddf963e186f43d
