apply plugin: 'com.android.library'
//apply plugin: 'com.novoda.bintray-release'

android {
    namespace 'com.luseen.spacenavigation'
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            tasks.withType(Javadoc).all { enabled = false }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "com.android.support:appcompat-v7:$rootProject.SUPPORT_LIBRARY_VERSION"
    implementation "com.android.support:support-v4:$rootProject.SUPPORT_LIBRARY_VERSION"
    implementation "com.android.support:design:$rootProject.SUPPORT_LIBRARY_VERSION"
}

//publish {
//    groupId = 'com.github.armcha'
//    artifactId = 'SpaceNavigationView'
//    publishVersion = '1.6.0'
//    desc = 'Spaces Navigation View'
//    licences = ['MIT']
//    website = 'https://github.com/armcha/Space-Navigation-View'
//}
